services:
  prepare_4_flask:
    container_name: prepare_4_flask
    build: .
    command: ["sh", "-c", "cd /app/app && flask run --host=0.0.0.0"]
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - 5000:5000

  prepare_4_redis:
    container_name: prepare_4_redis
    image: redis:7.0.4-alpine
  
  prepare_4_worker:
    container_name: prepare_4_worker
    build: .
    volumes:
      - .:/app
    command: ["sh", "-c", "cd /app/app && celery -A celery_app.celery worker -l info"]
    depends_on:
      - prepare_4_flask
      - prepare_4_redis
