services:
  prepare_4_flask:
    container_name: prepare_4_flask
    build: .
    command: ["flask", "run", "--host=0.0.0.0"]
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - 5000:5000
  